// 钉钉软件Web UI设计/src/app/components/SettingsPanel.tsx
import { User, Bell, Lock, Eye, Globe, Palette, HelpCircle, Info, LogOut, ChevronRight } from "lucide-react";
import { ScrollArea } from "@/app/components/ui/scroll-area";
import { Switch } from "@/app/components/ui/switch";
import { Button } from "@/app/components/ui/button";
import { Separator } from "@/app/components/ui/separator";

interface SettingItem {
  id: string;
  icon: React.ElementType;
  label: string;
  description?: string;
  type: "link" | "toggle";
  value?: boolean;
}

const accountSettings: SettingItem[] = [
  { id: "profile", icon: User, label: "个人资料", description: "修改头像、昵称等信息", type: "link" },
  { id: "account", icon: Lock, label: "账号与安全", description: "密码、手机号、邮箱", type: "link" },
];

const notificationSettings: SettingItem[] = [
  { id: "message", icon: Bell, label: "消息通知", value: true, type: "toggle" },
  { id: "meeting", icon: Bell, label: "会议通知", value: true, type: "toggle" },
  { id: "approval", icon: Bell, label: "审批通知", value: true, type: "toggle" },
  { id: "sound", icon: Bell, label: "声音提醒", value: false, type: "toggle" },
];

const privacySettings: SettingItem[] = [
  { id: "online", icon: Eye, label: "在线状态", description: "显示我的在线状态", type: "link" },
  { id: "read", icon: Eye, label: "已读回执", value: true, type: "toggle" },
  { id: "typing", icon: Eye, label: "正在输入", value: true, type: "toggle" },
];

const generalSettings: SettingItem[] = [
  { id: "language", icon: Globe, label: "语言", description: "简体中文", type: "link" },
  { id: "theme", icon: Palette, label: "主题", description: "跟随系统", type: "link" },
];

const otherSettings: SettingItem[] = [
  { id: "help", icon: HelpCircle, label: "帮助与反馈", type: "link" },
  { id: "about", icon: Info, label: "关于钉钉", description: "版本 7.0.0", type: "link" },
];

export function SettingsPanel() {
  return (
    <div className="flex-1 bg-[#F7F8FA]">
      <ScrollArea className="h-full">
        <div className="max-w-4xl mx-auto p-6 space-y-6">
          {/* Header */}
          <div>
            <h1 className="text-2xl mb-1">设置</h1>
            <p className="text-sm text-gray-500">管理你的账号和应用偏好设置</p>
          </div>

          {/* Account Settings */}
          <div className="bg-white rounded-lg p-4">
            <h2 className="text-base font-medium mb-4">账号设置</h2>
            <div className="space-y-1">
              {accountSettings.map((setting, index) => {
                const Icon = setting.icon;
                return (
                  <div key={setting.id}>
                    <button className="w-full flex items-center justify-between p-3 rounded-lg hover:bg-gray-50 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center">
                          <Icon className="w-5 h-5 text-blue-600" />
                        </div>
                        <div className="text-left">
                          <p className="text-sm font-medium">{setting.label}</p>
                          {setting.description && (
                            <p className="text-xs text-gray-500">{setting.description}</p>
                          )}
                        </div>
                      </div>
                      <ChevronRight className="w-5 h-5 text-gray-400" />
                    </button>
                    {index < accountSettings.length - 1 && <Separator />}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Notification Settings */}
          <div className="bg-white rounded-lg p-4">
            <h2 className="text-base font-medium mb-4">通知设置</h2>
            <div className="space-y-1">
              {notificationSettings.map((setting, index) => {
                const Icon = setting.icon;
                return (
                  <div key={setting.id}>
                    <div className="flex items-center justify-between p-3 rounded-lg hover:bg-gray-50 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-green-50 flex items-center justify-center">
                          <Icon className="w-5 h-5 text-green-600" />
                        </div>
                        <div className="text-left">
                          <p className="text-sm font-medium">{setting.label}</p>
                        </div>
                      </div>
                      <Switch defaultChecked={setting.value} />
                    </div>
                    {index < notificationSettings.length - 1 && <Separator />}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Privacy Settings */}
          <div className="bg-white rounded-lg p-4">
            <h2 className="text-base font-medium mb-4">隐私设置</h2>
            <div className="space-y-1">
              {privacySettings.map((setting, index) => {
                const Icon = setting.icon;
                return (
                  <div key={setting.id}>
                    <div className="flex items-center justify-between p-3 rounded-lg hover:bg-gray-50 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-purple-50 flex items-center justify-center">
                          <Icon className="w-5 h-5 text-purple-600" />
                        </div>
                        <div className="text-left">
                          <p className="text-sm font-medium">{setting.label}</p>
                          {setting.description && (
                            <p className="text-xs text-gray-500">{setting.description}</p>
                          )}
                        </div>
                      </div>
                      {setting.type === "toggle" ? (
                        <Switch defaultChecked={setting.value} />
                      ) : (
                        <ChevronRight className="w-5 h-5 text-gray-400" />
                      )}
                    </div>
                    {index < privacySettings.length - 1 && <Separator />}
                  </div>
                );
              })}
            </div>
          </div>

          {/* General Settings */}
          <div className="bg-white rounded-lg p-4">
            <h2 className="text-base font-medium mb-4">通用设置</h2>
            <div className="space-y-1">
              {generalSettings.map((setting, index) => {
                const Icon = setting.icon;
                return (
                  <div key={setting.id}>
                    <button className="w-full flex items-center justify-between p-3 rounded-lg hover:bg-gray-50 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-orange-50 flex items-center justify-center">
                          <Icon className="w-5 h-5 text-orange-600" />
                        </div>
                        <div className="text-left">
                          <p className="text-sm font-medium">{setting.label}</p>
                          {setting.description && (
                            <p className="text-xs text-gray-500">{setting.description}</p>
                          )}
                        </div>
                      </div>
                      <ChevronRight className="w-5 h-5 text-gray-400" />
                    </button>
                    {index < generalSettings.length - 1 && <Separator />}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Other Settings */}
          <div className="bg-white rounded-lg p-4">
            <h2 className="text-base font-medium mb-4">其他</h2>
            <div className="space-y-1">
              {otherSettings.map((setting, index) => {
                const Icon = setting.icon;
                return (
                  <div key={setting.id}>
                    <button className="w-full flex items-center justify-between p-3 rounded-lg hover:bg-gray-50 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-gray-50 flex items-center justify-center">
                          <Icon className="w-5 h-5 text-gray-600" />
                        </div>
                        <div className="text-left">
                          <p className="text-sm font-medium">{setting.label}</p>
                          {setting.description && (
                            <p className="text-xs text-gray-500">{setting.description}</p>
                          )}
                        </div>
                      </div>
                      <ChevronRight className="w-5 h-5 text-gray-400" />
                    </button>
                    {index < otherSettings.length - 1 && <Separator />}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Logout Button */}
          <div className="bg-white rounded-lg p-4">
            <Button variant="outline" className="w-full text-red-600 hover:text-red-700 hover:bg-red-50 border-red-200">
              <LogOut className="w-4 h-4 mr-2" />
              退出登录
            </Button>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}

// ruoyi-im-web/src/views/SettingsPanel.vue
<template>
  <div class="settings-panel">
    <div class="settings-content">
      <div class="settings-header">
        <h1 class="settings-title">设置</h1>
        <p class="settings-subtitle">管理你的账号和应用偏好设置</p>
      </div>

      <div class="settings-section">
        <h2 class="section-title">账号设置</h2>
        <div class="settings-list">
          <div
            v-for="(setting, index) in accountSettings"
            :key="setting.id"
            class="setting-item"
          >
            <button class="setting-btn" @click="handleSettingClick(setting)">
              <div class="setting-left">
                <div class="setting-icon icon-blue">
                  <el-icon><component :is="setting.icon" /></el-icon>
                </div>
                <div class="setting-info">
                  <p class="setting-label">{{ setting.label }}</p>
                  <p v-if="setting.description" class="setting-desc">{{ setting.description }}</p>
                </div>
              </div>
              <el-icon class="setting-arrow"><ArrowRight /></el-icon>
            </button>
            <div v-if="index < accountSettings.length - 1" class="setting-divider"></div>
          </div>
        </div>
      </div>

      <div class="settings-section">
        <h2 class="section-title">通知设置</h2>
        <div class="settings-list">
          <div
            v-for="(setting, index) in notificationSettings"
            :key="setting.id"
            class="setting-item"
          >
            <div class="setting-btn setting-toggle">
              <div class="setting-left">
                <div class="setting-icon icon-green">
                  <el-icon><component :is="setting.icon" /></el-icon>
                </div>
                <div class="setting-info">
                  <p class="setting-label">{{ setting.label }}</p>
                </div>
              </div>
              <el-switch v-model="setting.value" />
            </div>
            <div v-if="index < notificationSettings.length - 1" class="setting-divider"></div>
          </div>
        </div>
      </div>

      <div class="settings-section">
        <h2 class="section-title">隐私设置</h2>
        <div class="settings-list">
          <div
            v-for="(setting, index) in privacySettings"
            :key="setting.id"
            class="setting-item"
          >
            <button
              v-if="setting.type === 'link'"
              class="setting-btn"
              @click="handleSettingClick(setting)"
            >
              <div class="setting-left">
                <div class="setting-icon icon-purple">
                  <el-icon><component :is="setting.icon" /></el-icon>
                </div>
                <div class="setting-info">
                  <p class="setting-label">{{ setting.label }}</p>
                  <p v-if="setting.description" class="setting-desc">{{ setting.description }}</p>
                </div>
              </div>
              <el-icon class="setting-arrow"><ArrowRight /></el-icon>
            </button>
            <div v-else class="setting-btn setting-toggle">
              <div class="setting-left">
                <div class="setting-icon icon-purple">
                  <el-icon><component :is="setting.icon" /></el-icon>
                </div>
                <div class="setting-info">
                  <p class="setting-label">{{ setting.label }}</p>
                  <p v-if="setting.description" class="setting-desc">{{ setting.description }}</p>
                </div>
              </div>
              <el-switch v-model="setting.value" />
            </div>
            <div v-if="index < privacySettings.length - 1" class="setting-divider"></div>
          </div>
        </div>
      </div>

      <div class="settings-section">
        <h2 class="section-title">通用设置</h2>
        <div class="settings-list">
          <div
            v-for="(setting, index) in generalSettings"
            :key="setting.id"
            class="setting-item"
          >
            <button class="setting-btn" @click="handleSettingClick(setting)">
              <div class="setting-left">
                <div class="setting-icon icon-orange">
                  <el-icon><component :is="setting.icon" /></el-icon>
                </div>
                <div class="setting-info">
                  <p class="setting-label">{{ setting.label }}</p>
                  <p v-if="setting.description" class="setting-desc">{{ setting.description }}</p>
                </div>
              </div>
              <el-icon class="setting-arrow"><ArrowRight /></el-icon>
            </button>
            <div v-if="index < generalSettings.length - 1" class="setting-divider"></div>
          </div>
        </div>
      </div>

      <div class="settings-section">
        <h2 class="section-title">其他</h2>
        <div class="settings-list">
          <div
            v-for="(setting, index) in otherSettings"
            :key="setting.id"
            class="setting-item"
          >
            <button class="setting-btn" @click="handleSettingClick(setting)">
              <div class="setting-left">
                <div class="setting-icon icon-gray">
                  <el-icon><component :is="setting.icon" /></el-icon>
                </div>
                <div class="setting-info">
                  <p class="setting-label">{{ setting.label }}</p>
                  <p v-if="setting.description" class="setting-desc">{{ setting.description }}</p>
                </div>
              </div>
              <el-icon class="setting-arrow"><ArrowRight /></el-icon>
            </button>
            <div v-if="index < otherSettings.length - 1" class="setting-divider"></div>
          </div>
        </div>
      </div>

      <div class="settings-section">
        <el-button class="logout-btn">
          <el-icon><SwitchButton /></el-icon>
          退出登录
        </el-button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import {
  User,
  Lock,
  Bell,
  View,
  Location,
  Brush,
  QuestionFilled,
  InfoFilled,
  ArrowRight,
  SwitchButton
} from '@element-plus/icons-vue'

const accountSettings = ref([
  {
    id: 'profile',
    icon: User,
    label: '个人资料',
    description: '修改头像、昵称等信息',
    type: 'link'
  },
  {
    id: 'account',
    icon: Lock,
    label: '账号与安全',
    description: '密码、手机号、邮箱',
    type: 'link'
  }
])

const notificationSettings = ref([
  {
    id: 'message',
    icon: Bell,
    label: '消息通知',
    value: true,
    type: 'toggle'
  },
  {
    id: 'meeting',
    icon: Bell,
    label: '会议通知',
    value: true,
    type: 'toggle'
  },
  {
    id: 'approval',
    icon: Bell,
    label: '审批通知',
    value: true,
    type: 'toggle'
  },
  {
    id: 'sound',
    icon: Bell,
    label: '声音提醒',
    value: false,
    type: 'toggle'
  }
])

const privacySettings = ref([
  {
    id: 'online',
    icon: View,
    label: '在线状态',
    description: '显示我的在线状态',
    type: 'link'
  },
  {
    id: 'read',
    icon: View,
    label: '已读回执',
    value: true,
    type: 'toggle'
  },
  {
    id: 'typing',
    icon: View,
    label: '正在输入',
    value: true,
    type: 'toggle'
  }
])

const generalSettings = ref([
  {
    id: 'language',
    icon: Location,
    label: '语言',
    description: '简体中文',
    type: 'link'
  },
  {
    id: 'theme',
    icon: Brush,
    label: '主题',
    description: '跟随系统',
    type: 'link'
  }
])

const otherSettings = ref([
  {
    id: 'help',
    icon: QuestionFilled,
    label: '帮助与反馈',
    type: 'link'
  },
  {
    id: 'about',
    icon: InfoFilled,
    label: '关于钉钉',
    description: '版本 7.0.0',
    type: 'link'
  }
])

const handleSettingClick = (setting) => {
  console.log('Setting clicked:', setting)
}
</script>

<style scoped>
.settings-panel {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  background-color: #f7f8fa;
  overflow: hidden;
}

.settings-content {
  max-width: 896px;
  width: 100%;
  margin: 0 auto;
  padding: 24px;
  overflow-y: auto;
}

.settings-header {
  margin-bottom: 24px;

  .settings-title {
    font-size: 24px;
    font-weight: 600;
    color: #262626;
    margin: 0 0 4px 0;
  }

  .settings-subtitle {
    font-size: 14px;
    color: #8c8c8c;
    margin: 0;
  }
}

.settings-section {
  background: #fff;
  border-radius: 8px;
  padding: 16px;
  margin-bottom: 16px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
}

.section-title {
  font-size: 16px;
  font-weight: 500;
  color: #262626;
  margin: 0 0 16px 0;
}

.settings-list {
  display: flex;
  flex-direction: column;
}

.setting-item {
  position: relative;
}

.setting-btn {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px;
  border-radius: 8px;
  cursor: pointer;
  transition: background-color 0.2s ease;
  background: transparent;
  border: none;
  text-align: left;

  &:hover {
    background-color: #f5f5f5;
  }

  &.setting-toggle {
    cursor: default;

    &:hover {
      background-color: transparent;
    }
  }
}

.setting-left {
  display: flex;
  align-items: center;
  gap: 12px;
  flex: 1;
}

.setting-icon {
  width: 40px;
  height: 40px;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;

  .el-icon {
    font-size: 20px;
  }

  &.icon-blue {
    background-color: #e6f7ff;
    color: #1890ff;
  }

  &.icon-green {
    background-color: #f6ffed;
    color: #52c41a;
  }

  &.icon-purple {
    background-color: #f9f0ff;
    color: #722ed1;
  }

  &.icon-orange {
    background-color: #fff7e6;
    color: #fa8c16;
  }

  &.icon-gray {
    background-color: #f5f5f5;
    color: #595959;
  }
}

.setting-info {
  flex: 1;
}

.setting-label {
  font-size: 14px;
  font-weight: 500;
  color: #262626;
  margin: 0 0 2px 0;
}

.setting-desc {
  font-size: 12px;
  color: #8c8c8c;
  margin: 0;
}

.setting-arrow {
  font-size: 20px;
  color: #bfbfbf;
  flex-shrink: 0;
}

.setting-divider {
  height: 1px;
  background-color: #f0f0f0;
  margin: 0;
}

.logout-btn {
  width: 100%;
  color: #f5222d;
  border-color: #ffccc7;
  display: flex;
  align-items: center;
  gap: 4px;

  &:hover {
    color: #f5222d;
    background-color: #fff1f0;
    border-color: #ffccc7;
  }
}
</style>
